### ISSUE TITLE
Use of word "synchronous" in request-reply.md is ambiguous 

### ISSUE THREAD

**Issue by jldec** [projectriff/invoker-specification#5]
From `request-reply.md`

> When running in request / reply mode, a function invoker MUST behave as an http server and invoke its function in a synchronous manner.

I think I understand what you mean, but we already use "asynchronous" terminology with the [node function invoker](https://github.com/projectriff/node-function-invoker/) to mean `async` functions.

> Request-reply functions can also be asynchronous:
> 
> `module.exports = async (x) => x ** 2;`

My suggestion would be to stick to "request / reply" terminology which is simpler, and doesn't require specific understanding of terms like `synchronous`.

**Comment by ericbottard** [comment]
I think usage in the spec of "synchronous" / "asynchronous" trumps all specific meaning of those words in a specific language context. The intent here was to specify that the function MUST wait for a result to be produced and return it. Now, if the word _synchronous_ is not the best for that particular meaning, I'm happy to change it, but not on the sole reason that it could be understood as "the negation of keyword `async` in javascript", wdyt?

**Comment by jldec** [comment]
I think we should avoid the use of ambiguous terminology

In this case all we care about is that the **invoker** responds to a request with the result produced by the function triggered by that request.

We don't really care whether the invoker is implemented to assume that the function is always blocking until the result is returned (which may be what is understood from the description now), or if it is implemented in way that supports functions which first return a promise, and later resolve the promise.

IOW it's not necessarily the **function** that has to wait for the result, it's the invoker.
